opensilex-core:
    debug: true
    host: localhost
    port: 8080
    basePath: /opensilex-core/rest
    initPackages: []
    servicePackages:
        - org.opensilex.core.api.sample
        
opensilex-core-rdf4j:
    host: localhost
    port: 8080
    repository: repository
        
opensilex-core-mongo:
    host: localhost
    port: 27017
    database: database
    
